---
grails:
    profile: web
    codegen:
        defaultPackage: org.karajanresearch.oma
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
                  maxFileSize: 4000000000
                  maxRequestSize: 4000000000
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:

        springsecurity: # https://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_configuration
            # https://stackoverflow.com/questions/34641681/grails-rest-spring-security-plugin-does-not-store-generated-token-using-gorm-in
            useSecurityEventListener: true
            rest.token.storage.useGorm: true


            rest.token.storage.gorm.tokenDomainClassName: "org.karajanresearch.oma.AuthenticationToken"
            rest.token.storage.gorm.tokenValuePropertyName: "tokenValue"
            rest.token.storage.gorm.usernamePropertyName: "username"

    #grails.plugin.springsecurity.rememberMe.persistent = true
    #grails.plugin.springsecurity.rememberMe.persistentToken.domainClassName = 'org.karajanresearch.oma.PersistentLogin'


    gorm:
        multiTenancy:
            mode: DISCRIMINATOR
            tenantResolverClass: org.karajanresearch.oma.CurrentUserTenantResolver

endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

oma:
    dataDirectory:
        development: /home/martin/Workspace/oma/efs-local
        production: /efs-oma-digital

environments:
    development:
        dataSource:
            # dbCreate: create-drop
            # dbCreate: create-drop
            #url: jdbc:h2:./devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            # dbCreate: update
            dbCreate: none
            username: oma
            password: Xx7%nbpS9>y$4x2<
            driverClassName: org.postgresql.Driver
            dialect: PostgreSQLDialect
            url: jdbc:postgresql://oma-karajan-research-test.cvspe32jrws5.eu-central-1.rds.amazonaws.com:5432/oma

    test:
        dataSource:
            dbCreate: none
            // dbCreate: create-drop
            username: oma
            password: Xx7%nbpS9>y$4x2<
            driverClassName: org.postgresql.Driver
            dialect: PostgreSQLDialect
            url: jdbc:postgresql://oma-karajan-research-test.cvspe32jrws5.eu-central-1.rds.amazonaws.com:5432/oma

    production:
        dataSource:
            dbCreate: none
            username: oma
            password: Xx7%nbpS9>y$4x2<
            driverClassName: org.postgresql.Driver
            dialect: PostgreSQLDialect
            url: jdbc:postgresql://oma-karajan-research-test.cvspe32jrws5.eu-central-1.rds.amazonaws.com:5432/oma
